version: '3.8'

services:
  api:
    build: .
    ports:
      - "5569:5569"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data: