version: '3.8'

services:
  api:
    build: .
    ports:
      - "5569:5569"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"